### PR TITLE
Add device class and unit of measurement

### LINKED ISSUE #57: Variable not acting as sensor
This is more a question than an issue. I have a variable declared in yaml this way:
>  temp_dorm:
    name: T. Dorm
    value: 0
    restore: true
    attributes:
      min: 99
      max : 0
      date_min: ''
      date_max: ''
      icon: mdi:temperature-celsius
      unit_of_measurement: "°C"

I'm updating this variable with the value of a temperature sensor. Everything works fine, but I realize that the card showing the information of the variable is different than the card of the sensor. It doesn't show the min/mean/max values. So it looks it's not treating this variable as a sensor (with long term statistics and so on).
Is is due to the yaml definition or a restriction of the variables themself?

### LINKED ISSUE #65: RuntimeWarning: coroutine 'ConfigEntries.async_reload' was never awaited
2023-06-17 21:55:32.981 WARNING (MainThread) [py.warnings] /config/custom_components/variable/__init__.py:224: RuntimeWarning: coroutine 'ConfigEntries.async_reload' was never awaited
  hass.config_entries.async_reload(entry_id)

### PR DESCRIPTION
**Pull request by Snuffy2**
* Add Device Class, State Class, and Unit of Measurement for Sensors (Fixes #57)
* Add Device Class for Binary Sensors
* Add None as an option for Binary Sensors
* Fixed some other inconsistency errors

**Notes:** 
1.  If a Device Class for a Sensor is set, the Value must be of the type that is required by the Device Class (ex. for a Device Class of Duration the Value must be a Number). This is enforced both when creating the Sensor Variable and when updating the Value of the Sensor Variable with the `variable.update_sensor` service.
2.  If a Device Class for a Sensor is set and a Unit of Measurement is not set, Home Assistant will give a Warning.
3.  If the Device Class of a Sensor is changed and the new Device Class requires a different type of Value, the old Value will be cleared.

### CODE REVIEW

**Comment by Snuffy2** [comment]
@Wibias not sure if you want to release this as a beta first?

**Comment by Snuffy2** [comment]
Turns out it was the same root cause for all of the problems I was seeing and the fix was pretty small. I think it's ready for review again. Thanks.

**Comment by Wibias** [comment]
Ready for merge? If yes what do we do about flake error? Just ignore it? If yes feel free to add # noqa: C901 at the end of l19!

**Comment by Snuffy2** [comment]
Yes, I believe it is ready to go. I added the noqa line for now. I may split it up in the future to reduce complexity, but not terribly high on my priority list honestly.

**Pull request merged**
