### PR TITLE
correction in README.md

### PR DESCRIPTION
**Pull request by emufan**

### CODE REVIEW

**Comment by Wibias** [comment]
@iprak Is that how your set_entity works? Or is it still variable?

**Comment by emufan** [comment]
I tried it, and it is only working with `entity`.

**Comment by iprak** [comment]
`variable.set_variable` cannot be used for variable generated entities which have a different domain e.g. `sensor.custom_variable` since they don't exist under `variable` domain,

`variable.set_entity` should work on any entity.
`variable.set_variable` works as before only on variable entities.

**Comment by emufan** [comment]
That was not the double-check question from Wibias. The question was, if I corrected your example correctly. Where you by mistake used set_entity with param variable instead of entity. Please see files changed tab with my correction.

**Pull request merged**
