### PR TITLE
Change recorder_prefilter from submodule to subtree

### PR DESCRIPTION
**Pull request by Snuffy2**
Submodules don't work well with HA and HACS. Changing recorder_prefilter from submodule to subtree.

Without changing this to a subtree, #68 won't work properly.

### CODE REVIEW

**Comment by Snuffy2** [comment]
@Wibias not sure how you'd like to handle the linting errors as they are in the subtree and that is not code I can change.

**Comment by Wibias** [comment]
Uhm. Just also "_LOGGER.exception(...." or am I wrong?

**Comment by Wibias** [comment]
Uhm. Just also "_LOGGER.exception(...." or am I wrong? @Snuffy2

**Comment by Snuffy2** [comment]
Sorry, I'm not sure what you're asking.

**Pull request merged**
